duh

diff --git a/.github/workflows/pr-build-test.yaml b/.github/workflows/pr-build-test.yaml
--- a/.github/workflows/pr-build-test.yaml
+++ b/.github/workflows/pr-build-test.yaml
@@ -123,7 +123,7 @@ jobs:
                         npx apify validate-schema
                     fi
                     if [ -d ./actors ]; then
-                        cd ./actors && ls | xargs -P 8 -I {} sh -c 'cd {} && apify validate-schema || { echo "::error::Schema validation failed in actor: {}"; exit 1; }'
+                        cd ./actors && ls | xargs -P 8 -I {} sh -c 'cd {} && npx apify validate-schema || { echo "::error::Schema validation failed in actor: {}"; exit 1; }'
                     fi
 
             -   name: Test
