fix: vis -> validate-schema

diff --git a/.github/workflows/pr-build-test.yaml b/.github/workflows/pr-build-test.yaml
--- a/.github/workflows/pr-build-test.yaml
+++ b/.github/workflows/pr-build-test.yaml
@@ -120,11 +120,11 @@ jobs:
                     # let apify cli initialize its config to avoid race conditions with xargs
                     apify --version >/dev/null 2>&1
                     if [ -d ./.actor ]; then
-                        apify vis
+                        apify validate-schema
                     fi
                     if [ -d ./actors ]; then
-                        # `apify vis` fail code is changed from 1 to 255 so xargs aborts on first error.
-                        cd ./actors && ls | xargs -P 8 -I {} sh -c 'cd {} && apify vis || exit 255'
+                        # `apify validate-schema` fail code is changed from 1 to 255 so xargs aborts on first error.
+                        cd ./actors && ls | xargs -P 8 -I {} sh -c 'cd {} && apify validate-schema || exit 255'
                     fi
 
             -   name: Test
