fix: use apify-cli

diff --git a/.github/workflows/pr-build-test.yaml b/.github/workflows/pr-build-test.yaml
--- a/.github/workflows/pr-build-test.yaml
+++ b/.github/workflows/pr-build-test.yaml
@@ -117,12 +117,12 @@ jobs:
                     if [ ! -d "node_modules/apify-cli" ]; then
                         echo "::warning::apify-cli is not installed as an npm dependency. Improve CI speed by installing it"
                     fi
-                    npx --yes apify telemetry disable
+                    npx --yes apify-cli telemetry disable
                     if [ -d ./.actor ]; then
-                        npx apify validate-schema
+                        npx apify-cli validate-schema
                     fi
                     if [ -d ./actors ]; then
-                        cd ./actors && ls | xargs -P 8 -I {} sh -c 'cd {} && npx apify validate-schema || { echo "::error::Schema validation failed in actor: {}"; exit 1; }'
+                        cd ./actors && ls | xargs -P 8 -I {} sh -c 'cd {} && npx apify-cli validate-schema || { echo "::error::Schema validation failed in actor: {}"; exit 1; }'
                     fi
 
             -   name: Test
